<?php
/**
 * C3 Media Ltd
 *
 * @title 		Environment Banner.
 * @category	C3
 * @package 	C3_EnvironmentBanner
 * @author		C3 Development Team <development@c3media.co.uk>
 * @copyright   Copyright (c) 2014 C3 Media Ltd (http://www.c3media.co.uk)
 */

/** @var C3_EnvironmentBanner_Helper_Data $helper */
$helper = Mage::helper("c3_environmentbanner");
if ($helper->isDisplayFrontendBanner()):
    $env = $helper->getEnvironment();
    $cols = $helper->getEnvColours();
?>
<style type="text/css">
    .ribbon-wrapper {
        width: 160px;
        height: 160px;
        overflow: hidden;
        position: fixed;
        top: 0px;
        right: 0px;
        z-index: 10000;
    }

    .ribbon-inner {
        font: bold 18px Sans-Serif;
        color: #333;
        text-align: center;
        text-shadow:     rgba(255,255,255,0.5) 0px 1px 0px;
        -webkit-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -o-transform: rotate(45deg);
        position: relative;
        padding: 20px 0px;
        left: 3px;
        top: 22px;
        width: 210px;
        opacity: 0.9;
    }
    .ribbon-inner.<?php echo $env ?> {
        background-color: <?php echo $cols->getFeLighterBgcolor() ?>;
        background-image: -webkit-gradient(linear, left top, left bottom, from(<?php echo $cols->getFeLighterBgcolor() ?>), to(<?php echo $cols->getFeBgcolor() ?>));
        background-image: -webkit-linear-gradient(top, <?php echo $cols->getFeLighterBgcolor() ?>, <?php echo $cols->getFeBgcolor() ?>);
        background-image: -moz-linear-gradient(top, <?php echo $cols->getFeLighterBgcolor() ?>, <?php echo $cols->getFeBgcolor() ?>);
        background-image: -ms-linear-gradient(top, <?php echo $cols->getFeLighterBgcolor() ?>, <?php echo $cols->getFeBgcolor() ?>);
        background-image: -o-linear-gradient(top, <?php echo $cols->getFeLighterBgcolor() ?>, <?php echo $cols->getFeBgcolor() ?>);
        color: <?php echo $cols->getFeColor() ?>;
    }
</style>
<div class="ribbon-wrapper" onclick="document.getElementById('envbanner').style.display = 'none';" id="envbanner"><div class="ribbon-inner <?php echo $env ?>" title="click to hide"><?php echo ucfirst($env) ?></div></div>

<?php endif; ?>