<?php
/**
 * C3 Media Ltd
 *
 * @title 		Environment Banner.
 * @category	C3
 * @package 	C3_EnvironmentBanner
 * @author		C3 Development Team <development@c3media.co.uk>
 * @copyright   Copyright (c) 2014 C3 Media Ltd (http://www.c3media.co.uk)
 */

$helper = Mage::helper("c3_environmentbanner");
if ($helper->isDisplayFrontendBanner()):
    $env = $helper->getEnvironment();
?>
<style type="text/css">
    .ribbon-wrapper {
        width: 160px;
        height: 160px;
        overflow: hidden;
        position: fixed;
        top: 0px;
        right: 0px;
        z-index: 10000;
    }

    .ribbon-inner {
        font: bold 18px Sans-Serif;
        color: #333;
        text-align: center;
        text-shadow: rgba(255,255,255,0.5) 0px 1px 0px;
        -webkit-transform: rotate(45deg);
        -moz-transform: rotate(45deg);
        -ms-transform: rotate(45deg);
        -o-transform: rotate(45deg);
        position: relative;
        padding: 20px 0px;
        left: 3px;
        top: 22px;
        width: 210px;
    }
<?php if ($env == 'staging'): ?>
    .ribbon-inner.staging {
        background-color: #dc8f00;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#dc8f00), to(#d45d12));
        background-image: -webkit-linear-gradient(top, #dc8f00, #d45d12);
        background-image: -moz-linear-gradient(top, #dc8f00, #d45d12);
        background-image: -ms-linear-gradient(top, #dc8f00, #d45d12);
        background-image: -o-linear-gradient(top, #dc8f00, #d45d12);
        color: #3f1517;
    }
<?php endif; if ($env == 'development'): ?>
    .ribbon-inner.development {
        background-color: #BFDC7A;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#BFDC7A), to(#8EBF45));
        background-image: -webkit-linear-gradient(top, #BFDC7A, #8EBF45);
        background-image: -moz-linear-gradient(top, #BFDC7A, #8EBF45);
        background-image: -ms-linear-gradient(top, #BFDC7A, #8EBF45);
        background-image: -o-linear-gradient(top, #BFDC7A, #8EBF45);
        color: #6a6340;
    }
<?php endif; if ($env == 'preview'): ?>
    .ribbon-inner.preview {
        background-color: #a080d9;
        background-image: -webkit-gradient(linear, left top, left bottom, from(#a080d9), to(#7c43bf));
        background-image: -webkit-linear-gradient(top, #a080d9, #7c43bf);
        background-image: -moz-linear-gradient(top, #a080d9, #7c43bf);
        background-image: -ms-linear-gradient(top, #a080d9, #7c43bf);
        background-image: -o-linear-gradient(top, #a080d9, #7c43bf);
        color: #47236a;
    }
<?php endif; ?>
</style>
<div class="ribbon-wrapper" onclick="document.getElementById('envbanner').style.display = 'none';" id="envbanner"><div class="ribbon-inner <?php echo $env ?>" title="click to hide"><?php echo ucfirst($env) ?></div></div>

<?php endif; ?>