<?php
/**
 * C3 Media Ltd
 *
 * @title 		Environment Banner.
 * @category	C3
 * @package 	C3_EnvironmentBanner
 * @author		C3 Development Team <development@c3media.co.uk>
 * @copyright   Copyright (c) 2014 C3 Media Ltd (http://www.c3media.co.uk)
 */

/** @modification Setting banner colour based on environment. Also inserts name of environment after logo */
/** @var C3_EnvironmentBanner_Helper_Data $envHelper */
$envHelper = Mage::helper("c3_environmentbanner");
$env = $envHelper->getEnvironment();
$cols = $envHelper->getEnvColours();
?>
<style type="text/css">
    h2.env {
        float: left;
        margin-top: 13px;
        color: white;
    }
<?php
// Change colour of heading if that option is turned on
if ($envHelper->isDisplayAdminBanner()):
?>
    .ebborder {
        position:fixed;
        z-index: 10000;
    }
    #ebtop,#ebbottom {
        left:0;
        width:100%;
        height:3px;
    }
    #ebtop {
        top:0;
    }
    #ebbottom {
        bottom:0;
    }
    #ebleft,#ebright {
        top:0;
        height:100%;
        width:3px;
    }
    #ebleft {
        left:0;
    }
    #ebright {
        right:0;
    }

    .header {
        background-color: <?php echo $cols->getBeLighterColor() ?>;
        background-image: -webkit-gradient(linear, left top, left bottom, from(<?php echo $cols->getBeLighterColor() ?>), to(<?php echo $cols->getBeColor() ?>));
        background-image: -webkit-linear-gradient(top, <?php echo $cols->getBeLighterColor() ?>, <?php echo $cols->getBeColor() ?>);
        background-image: -moz-linear-gradient(top, <?php echo $cols->getBeLighterColor() ?>, <?php echo $cols->getBeColor() ?>);
        background-image: -ms-linear-gradient(top, <?php echo $cols->getBeLighterColor() ?>, <?php echo $cols->getBeColor() ?>);
        background-image: -o-linear-gradient(top, <?php echo $cols->getBeLighterColor() ?>, <?php echo $cols->getBeColor() ?>);
    }
    .ebborder {
        background-color: <?php echo $cols->getBeBorderColor() ?>;
    }
<?php endif; ?>
</style>
<?php
/** @var $this Mage_Adminhtml_Block_Page_Header */
?>
<div id="ebtop" class="ebborder"></div>
<div id="ebbottom" class="ebborder"></div>
<div id="ebleft" class="ebborder"></div>
<div id="ebright" class="ebborder"></div>
<div class="header-top">
    <a href="<?php echo $this->getHomeLink() ?>"><img src="<?php echo $this->getSkinUrl('images/'  . $envHelper->getAdminLogoFilename()) ?>" alt="<?php echo $this->__('Magento Logo') ?>" class="logo"/><?php if ($envHelper->isDisplayAdminEnv()) { echo '<h2 class="env">'.ucfirst($env).'</h2>'; } ?></a>
    <div class="header-right">
        <p class="super">
            <?php echo $this->__("Logged in as %s", $this->escapeHtml($this->getUser()->getUsername())) ?><span class="separator">|</span><?php echo $this->formatDate(null, 'full') ?><span class="separator">|</span><a href="http://golinks.magento.com/CE15" onclick="this.target='_blank'" class="go-try"><?php echo $this->__('Try Magento Go for Free') ?></a><span class="separator">|</span><a href="<?php echo $this->getLogoutLink() ?>" class="link-logout"><?php echo $this->__('Log Out') ?></a>
        </p>
        <?php if ( Mage::getSingleton('admin/session')->isAllowed('admin/global_search') ): ?>
            <fieldset>
                <legend>Search</legend>
            <span id="global_search_indicator" class="autocomplete-indicator" style="display: none">
                <img src="<?php echo $this->getSkinUrl('images/ajax-loader.gif') ?>" alt="<?php echo $this->__('Loading...') ?>" class="v-middle"/>
            </span>
                <?php $defSearch = $this->__('Global Record Search') ?>
                <input id="global_search" name="query" type="text" class="input-text" value="<?php if(!empty($query)): ?><?php echo $query ?><?php else: ?><?php echo $defSearch ?><?php endif ?>" onfocus="if(this.value=='<?php echo $defSearch ?>')this.value=''; " onblur="if(this.value=='')this.value='<?php echo $defSearch ?>';" />
                <div id="global_search_autocomplete" class="autocomplete"></div>
                <script type="text/javascript">
                    new Ajax.Autocompleter(
                        'global_search',
                        'global_search_autocomplete',
                        '<?php echo $this->getUrl('adminhtml/index/globalSearch') ?>',
                        {
                            paramName:"query",
                            minChars:2,
                            indicator:"global_search_indicator",
                            updateElement:getSelectionId,
                            evalJSON:'force'
                        }
                    );
                    function getSelectionId(li) {
                        location.href = li.getAttribute('url');
                    }
                </script>
            </fieldset>
        <?php endif; ?>
    </div>
</div>
